version: '3'
services:
  user-mongo:
     image: mongo
     network_mode: host
     ports:
       - "27017:27017"
     environment:
       MONGO_DATABASE: DepartmentDB
       MONGO_PORT: 27017
       MONGO_HOST: 127.0.0.1

  webapp4:
     image: webapp4-service
     build: 
       context: webapp4/
     depends_on:
       - user-mongo
     ports:
       - "8084:8084"
     network_mode: host

       


     
     
     
